import {
  EducationLevel,
  ImmigrationStatus,
  TimeInSpain,
  UserProfile,
} from '../types';

export interface GoldenTestCase {
  id: string;
  description: string;
  profile: UserProfile;
  expectedTemplateKey: string;
  acceptedTemplateKeys?: string[];
  strictMode?: boolean;
  reason: string;
}

const baseProfile: UserProfile = {
  firstName: 'Test',
  lastName: 'User',
  nationality: 'Argentina',
  age: 30,
  educationLevel: EducationLevel.UNIVERSITY,
  entryDate: '2024-09-01',
  currentStatus: ImmigrationStatus.TOURIST,
  timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
  province: 'Madrid',
  hasCriminalRecord: false,
  hasFamilyInSpain: false,
  familyDetails: '',
  isEmpadronado: false,
  jobSituation: 'Buscando opciones',
  comments: '',
  locationStatus: 'spain',
  familyNationality: undefined,
  familyRelation: undefined,
  primaryGoal: 'reside_work',
};

const buildProfile = (overrides: Partial<UserProfile>): UserProfile => ({
  ...baseProfile,
  ...overrides,
});

export const goldenTestCases: GoldenTestCase[] = [
  {
    id: 'CASE_001',
    description: 'Turista recién llegada con admisión a máster y fondos demostrables',
    profile: buildProfile({
      nationality: 'Argentina',
      currentStatus: ImmigrationStatus.TOURIST,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      jobSituation: 'Turista con carta de admisión a máster presencial y seguro médico',
      comments: 'Quiere cambiar a estancia de estudios y ya tiene matrícula y fondos',
      isEmpadronado: false,
      primaryGoal: 'study',
    }),
    expectedTemplateKey: 'ESTUDIAR EN ESPAÑA',
    strictMode: true,
    reason: 'Cambio de turista a estancia de estudios con admisión válida.',
  },
  {
    id: 'CASE_002',
    description: 'Estudiante de máster con oferta laboral en Madrid',
    profile: buildProfile({
      nationality: 'Chile',
      currentStatus: ImmigrationStatus.STUDENT,
      timeInSpain: TimeInSpain.TWO_TO_THREE_YEARS,
      entryDate: '2022-09-15',
      jobSituation: 'Oferta indefinida en empresa tecnológica (45k) tras terminar máster',
      isEmpadronado: true,
      comments: 'Busca pasar de estancia de estudios a permiso de trabajo por cuenta ajena',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'MODIFICAR DE ESTUDIOS A CUENTA AJENA',
    strictMode: true,
    reason: 'Modificación tras estudios con contrato de trabajo firmado.',
  },
  {
    id: 'CASE_003',
    description: 'Renovación de estancia para seguir el mismo grado universitario',
    profile: buildProfile({
      nationality: 'México',
      currentStatus: ImmigrationStatus.STUDENT,
      timeInSpain: TimeInSpain.ONE_TO_TWO_YEARS,
      entryDate: '2023-09-20',
      jobSituation: 'Estudiante a tiempo completo con recursos económicos suficientes',
      comments: 'Sigue matriculado en el mismo grado y necesita prorrogar la estancia',
      isEmpadronado: true,
      primaryGoal: 'study',
    }),
    expectedTemplateKey: 'RENOVACIÓN DE ESTUDIOS',
    reason: 'Continúa los mismos estudios y cumple requisitos de renovación.',
  },
  {
    id: 'CASE_004',
    description: 'Irregular 3+ años con oferta de trabajo firmada y empadronamiento',
    profile: buildProfile({
      nationality: 'Perú',
      currentStatus: ImmigrationStatus.IRREGULAR,
      timeInSpain: TimeInSpain.MORE_THAN_THREE_YEARS,
      entryDate: '2021-01-10',
      isEmpadronado: true,
      jobSituation: 'Oferta laboral indefinida con contrato a jornada completa',
      comments: 'Empadronado más de 3 años, oferta y medios para arraigo social',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'ARRAIGO SOCIAL',
    strictMode: true,
    reason: 'Permanencia >3 años + oferta laboral y empadronamiento continuo.',
  },
  {
    id: 'CASE_005',
    description: 'Irregular 3+ años con pruebas de relación laboral previa',
    profile: buildProfile({
      nationality: 'Bolivia',
      currentStatus: ImmigrationStatus.IRREGULAR,
      timeInSpain: TimeInSpain.MORE_THAN_THREE_YEARS,
      entryDate: '2020-08-01',
      isEmpadronado: true,
      jobSituation: 'Denuncia con acta de Inspección y nóminas de 6 meses',
      comments: 'Aporta pruebas laborales para acogerse a arraigo sociolaboral',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'ARRAIGO SOCIOLABORAL',
    reason: 'Acredita permanencia y relación laboral demostrable.',
  },
  {
    id: 'CASE_006',
    description: 'Irregular 3 años con preinscripción a curso oficial de 600h',
    profile: buildProfile({
      nationality: 'Marruecos',
      currentStatus: ImmigrationStatus.IRREGULAR,
      timeInSpain: TimeInSpain.MORE_THAN_THREE_YEARS,
      entryDate: '2021-06-05',
      isEmpadronado: true,
      jobSituation: 'Sin contrato, pero con preinscripción a formación reglada',
      comments: 'Busca arraigo socioformativo y tiene medios económicos básicos',
      primaryGoal: 'study',
    }),
    expectedTemplateKey: 'ARRAIGO SOCIOFORMATIVO',
    reason: 'Permanencia >3 años y compromiso de formación reglada.',
  },
  {
    id: 'CASE_007',
    description: 'Progenitor de menor español, irregular pero empadronado',
    profile: buildProfile({
      nationality: 'Colombia',
      age: 28,
      currentStatus: ImmigrationStatus.IRREGULAR,
      timeInSpain: TimeInSpain.TWO_TO_THREE_YEARS,
      entryDate: '2022-04-12',
      hasFamilyInSpain: true,
      familyNationality: 'spanish_eu',
      familyRelation: 'child',
      familyDetails: 'Hijo nacido en Madrid con nacionalidad española',
      isEmpadronado: true,
      jobSituation: 'Cuida a su hijo y trabaja ocasionalmente en limpieza',
      comments: 'Solicita residencia por arraigo familiar como progenitor de menor español',
      primaryGoal: 'family',
    }),
    expectedTemplateKey: 'ARRAIGO FAMILIAR',
    strictMode: true,
    reason: 'Padre/madre de menor español con convivencia y empadronamiento.',
  },
  {
    id: 'CASE_008',
    description: 'Cónyuge de ciudadano español, casados y viviendo en Madrid',
    profile: buildProfile({
      nationality: 'Venezuela',
      currentStatus: ImmigrationStatus.TOURIST,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      hasFamilyInSpain: true,
      familyNationality: 'spanish_eu',
      familyRelation: 'spouse',
      familyDetails: 'Matrimonio inscrito, viven juntos y empadronados',
      isEmpadronado: true,
      jobSituation: 'Turista con intención de residir junto a su cónyuge',
      comments: 'Quiere tarjeta comunitaria como cónyuge de español',
      primaryGoal: 'family',
    }),
    expectedTemplateKey: 'FAMILIAR UE 2025',
    acceptedTemplateKeys: ['ARRAIGO FAMILIAR'],
    strictMode: true,
    reason: 'Tarjeta de familiar de ciudadano de la UE por matrimonio con español.',
  },
  {
    id: 'CASE_009',
    description: 'Pareja de hecho registrada con ciudadano español',
    profile: buildProfile({
      nationality: 'Brasil',
      currentStatus: ImmigrationStatus.TOURIST,
      timeInSpain: TimeInSpain.ONE_TO_TWO_YEARS,
      hasFamilyInSpain: true,
      familyNationality: 'spanish_eu',
      familyRelation: 'registered_partner',
      familyDetails: 'Pareja de hecho inscrita en comunidad autónoma',
      isEmpadronado: true,
      jobSituation: 'Trabaja remoto para empresa en origen',
      comments: 'Busca tarjeta comunitaria por pareja de hecho',
      primaryGoal: 'family',
    }),
    expectedTemplateKey: 'PAREJA DE HECHO',
    acceptedTemplateKeys: ['FAMILIAR UE 2025'],
    reason: 'Pareja de hecho registrada con ciudadano español/UE.',
  },
  {
    id: 'CASE_010',
    description: 'Ingeniero remoto con salario alto desde empresa USA, vive fuera',
    profile: buildProfile({
      nationality: 'Estados Unidos',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      hasFamilyInSpain: false,
      jobSituation: 'Contrato remoto full time 120k USD con empresa extranjera',
      comments: 'Quiere residir en España manteniendo empleo remoto',
      isEmpadronado: false,
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'NÓMADA DIGITAL',
    strictMode: true,
    reason: 'Cumple perfil de permiso para teletrabajadores internacionales.',
  },
  {
    id: 'CASE_011',
    description: 'Inversor con 600k€ para comprar vivienda en Barcelona',
    profile: buildProfile({
      nationality: 'Canadá',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      hasFamilyInSpain: false,
      jobSituation: 'Inversor con fondos bancarios certificados para compra inmobiliaria',
      comments: 'Planea invertir 600k€ en inmueble y residir en España',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'RESIDENCIA PARA INVERSORES',
    reason: 'Cumple umbral de inversión para visa de inversor.',
  },
  {
    id: 'CASE_012',
    description: 'Oferta como profesional altamente cualificado en multinacional',
    profile: buildProfile({
      nationality: 'India',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      jobSituation: 'Oferta de data scientist en multinacional, salario 55k€',
      comments: 'Empresa grande quiere tramitar permiso HQ, no está en España aún',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'RESIDENCIA PARA PROFESIONAL ALTAMENTE CUALIFICADO',
    strictMode: true,
    reason: 'Oferta cualificada con salario alto y empresa elegible.',
  },
  {
    id: 'CASE_013',
    description: 'Quiere emigrar sin pasaporte UE y busca opciones iniciales',
    profile: buildProfile({
      nationality: 'Ecuador',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      hasFamilyInSpain: false,
      jobSituation: 'Analiza opciones de visado antes de viajar',
      comments: 'No tiene ciudadanía UE ni oferta; busca vías legales de entrada',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'EMIGRAR SIN PASAPORTE EUROPEO',
    reason: 'Necesita guía general de opciones para no comunitarios.',
  },
  {
    id: 'CASE_014',
    description: 'Solicitante de asilo con miedo creíble y pruebas',
    profile: buildProfile({
      nationality: 'Venezuela',
      currentStatus: ImmigrationStatus.ASYLUM_SEEKER,
      timeInSpain: TimeInSpain.ONE_TO_TWO_YEARS,
      jobSituation: 'Esperando resolución, con NIE de solicitante',
      comments: 'Aporta pruebas de persecución política, necesita orientación',
      isEmpadronado: true,
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'ASILO',
    strictMode: true,
    reason: 'Procedimiento específico de protección internacional.',
  },
  {
    id: 'CASE_015',
    description: 'Quiere trabajar mientras tramita tarjeta comunitaria en curso',
    profile: buildProfile({
      nationality: 'Paraguay',
      currentStatus: ImmigrationStatus.REGULAR,
      timeInSpain: TimeInSpain.ONE_TO_TWO_YEARS,
      hasFamilyInSpain: true,
      familyNationality: 'spanish_eu',
      familyRelation: 'spouse',
      jobSituation: 'Expediente de tarjeta comunitaria presentado, sin resolución',
      comments: 'Pregunta si puede trabajar mientras la residencia está en trámite',
      isEmpadronado: true,
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'TRABAJAR CON RESIDENCIA DE FAMILIAR DE CIUDADANO DE LA UE EN TRÁMITE',
    acceptedTemplateKeys: ['PUEDO TRABAJAR CON LA RESIDENCIA EN TRÁMITE'],
    reason: 'Consulta específica sobre derecho a trabajar durante el trámite.',
  },
  {
    id: 'CASE_016',
    description: 'Nieto de español de origen que acredita actas para LMD',
    profile: buildProfile({
      nationality: 'Argentina',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      hasFamilyInSpain: false,
      jobSituation: 'Reúne partidas y actas para acreditar ascendencia',
      comments: 'Abuelo español de origen, quiere aplicar a Ley de Memoria Democrática',
      primaryGoal: 'family',
    }),
    expectedTemplateKey: 'LEY DE MEMORIA DEMOCRÁTICA (LMD)',
    strictMode: true,
    reason: 'Aplicación por ascendencia bajo LMD con actas preparadas.',
  },
  {
    id: 'CASE_017',
    description: 'Residente legal 2 años (iberoamericano) solicita nacionalidad',
    profile: buildProfile({
      nationality: 'Colombia',
      currentStatus: ImmigrationStatus.REGULAR,
      timeInSpain: TimeInSpain.TWO_TO_THREE_YEARS,
      entryDate: '2022-11-01',
      jobSituation: 'Contrato indefinido y padrón estable',
      comments: 'Cumple 2 años de residencia legal como iberoamericano',
      isEmpadronado: true,
      primaryGoal: 'nationality',
    }),
    expectedTemplateKey: 'NACIONALIDAD 2024',
    reason: 'Cumple plazo reducido de 2 años para iberoamericanos.',
  },
  {
    id: 'CASE_018',
    description: 'Casado con española, 1 año de residencia y matrimonio inscrito',
    profile: buildProfile({
      nationality: 'Uruguay',
      currentStatus: ImmigrationStatus.REGULAR,
      timeInSpain: TimeInSpain.ONE_TO_TWO_YEARS,
      hasFamilyInSpain: true,
      familyNationality: 'spanish_eu',
      familyRelation: 'spouse',
      jobSituation: 'Trabaja con contrato parcial; matrimonio inscrito hace 18 meses',
      comments: 'Quiere tramitar nacionalidad por matrimonio con española',
      isEmpadronado: true,
      primaryGoal: 'nationality',
    }),
    expectedTemplateKey: 'NACIONALIDAD POR MATRIMONIO',
    reason: 'Cónuge de española con 1+ año de residencia y matrimonio inscrito.',
  },
  {
    id: 'CASE_019',
    description: 'Emprendedor con plan de negocio y capital propio',
    profile: buildProfile({
      nationality: 'Estados Unidos',
      currentStatus: ImmigrationStatus.OTHER,
      timeInSpain: TimeInSpain.LESS_THAN_1_YEAR,
      locationStatus: 'origin',
      jobSituation: 'Plan de negocio innovador con inversión propia de 80k€',
      comments: 'Quiere establecer startup tecnológica en Barcelona',
      primaryGoal: 'reside_work',
    }),
    expectedTemplateKey: 'EMPRENDER EN ESPAÑA',
    reason: 'Proyecto emprendedor con inversión y plan viable.',
  },
  {
    id: 'CASE_020',
    description: 'Residente legal quiere traer a su cónyuge y menor desde origen',
    profile: buildProfile({
      nationality: 'Senegal',
      currentStatus: ImmigrationStatus.REGULAR,
      timeInSpain: TimeInSpain.MORE_THAN_THREE_YEARS,
      hasFamilyInSpain: true,
      familyNationality: 'non_eu',
      familyRelation: 'spouse',
      jobSituation: 'Contrato estable y vivienda adecuada',
      comments: 'Quiere reagrupar a su esposa y su hijo menor desde origen',
      isEmpadronado: true,
      primaryGoal: 'family',
    }),
    expectedTemplateKey: 'REAGRUPACIÓN FAMILIAR',
    reason: 'Titular con medios suficientes para reagrupar familiares no UE.',
  },
];
